---
- hosts: localhost
  become: true
  tasks:
    - name: Uninstall old versions Docker
      yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent
    - name: Install required packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: latest
    - name: create a Docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    - name: install Docker CE
      yum:
        name: docker-ce
        state: latest
    - name: Disable nightly repository
      shell: yum-config-manager --disable docker-ce-nightly
    - name: docker start
      service: name=docker state=started
    - name: docker image pull and run container
      shell: docker run -d -p 8181:8080 jenkins
